### ISSUE TITLE
example AP rename code always terminates with an error

### ISSUE THREAD

**Issue by chose2017** [aruba/pycentral#5]
The example code always terminates with an error

AP_SETTINGS_CSV - ERROR - Failed to update ap settings for APs []

it looks like its just not checking for an empty array.   Perhaps we could test for this condition. 

  unkown_aps = list(set(all_aps) - set(success_aps + failed_aps))
    failed_aps = failed_aps + unkown_aps
    print("")
    LOGGER.error("Failed to update ap settings for APs %s" % failed_aps)

**Comment by karthikeyan-dhandapani** [comment]
@chose2017 Thanks for the issue. Will fix it shortly.

**Comment by karthikeyan-dhandapani** [comment]
Will be merged to the Master branch after testing and the changes will be part of the next release.
